image: node:16

pipelines:
  default:
    - step:
        name: Build
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts:
          - dist/**
    - step:
        name: Deploy Artifacts to Development Server
        deployment: development
        script:
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: root
              SERVER: 143.198.88.40
              REMOTE_PATH: '/var/www/html'
              LOCAL_PATH: 'dist/*'